# Generated by Django 3.0.5 on 2020-08-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatchannel',
            name='team_no',
        ),
        migrations.RemoveField(
            model_name='code',
            name='user_no',
        ),
        migrations.RemoveField(
            model_name='commentcode',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentcode',
            name='team_no',
        ),
        migrations.RemoveField(
            model_name='commentproblem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentproblem',
            name='team_no',
        ),
        migrations.RemoveField(
            model_name='joinedteam',
            name='team_no',
        ),
        migrations.RemoveField(
            model_name='joinedteam',
            name='user_no',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team_no',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatChannel',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='CommentCode',
        ),
        migrations.DeleteModel(
            name='CommentProblem',
        ),
        migrations.DeleteModel(
            name='JoinedTeam',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
