# Generated by Django 3.0.5 on 2020-08-19 10:02

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, validators=[board.models.min_length_5_validator]),
        ),
    ]
