# Generated by Django 3.1 on 2020-08-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200826_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code_no',
            new_name='problem_no',
        ),
    ]
