# Generated by Django 3.1 on 2020-08-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200827_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatchannel',
            name='team_no',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatChannel',
        ),
    ]
